services:
  # External database - no local PostgreSQL container needed
  # Database host: postgres.local.pro4.es

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: therapy-backend
    environment:
      DATABASE_URL: postgresql://therapy_user:therapy_password@postgres.local.pro4.es:5432/therapy_system
      JWT_SECRET_KEY: your-secret-key-here-change-in-production
      ENVIRONMENT: development
      DB_HOST: postgres.local.pro4.es
      DB_PORT: 5432
      DB_NAME: therapy_system
      DB_USER: therapy_user
      DB_PASSWORD: therapy_password
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - therapy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolallowheaders=Authorization,Content-Type"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolalloworiginlist=http://localhost:3000,http://app.localhost"
      - "traefik.http.middlewares.backend-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.backend-cors.headers.addvaryheader=true"
      - "traefik.http.routers.backend.middlewares=backend-cors"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: therapy-frontend
    environment:
      REACT_APP_API_URL: http://api.localhost
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - therapy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.0
    container_name: therapy-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - therapy-network

# No local volumes needed - using external database

networks:
  therapy-network:
    driver: bridge