services:
  # External database - no local PostgreSQL container needed
  # Database host: postgres.local.pro4.es

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: therapy-backend
    environment:
      DATABASE_URL: postgresql://therapy_user:therapy_password@postgres.local.pro4.es:5432/therapy_system
      JWT_SECRET_KEY: your-secret-key-here-change-in-production
      ENVIRONMENT: development
      DB_HOST: postgres.local.pro4.es
      DB_PORT: 5432
      DB_NAME: therapy_system
      DB_USER: therapy_user
      DB_PASSWORD: therapy_password
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - therapy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: therapy-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - therapy-network

  # For Traefik configuration, see docker-compose.traefik.yml
  # To run with Traefik: docker-compose -f docker-compose.traefik.yml up

# No local volumes needed - using external database

networks:
  therapy-network:
    driver: bridge