#!/bin/bash

echo "=== Instrukcja kodowania kubeconfig dla GitHub Actions ==="
echo ""
echo "1. Na serwerze z Kubernetes (207.180.229.128):"
echo ""
echo "   # Eksportuj kubeconfig"
echo "   kubectl config view --raw > ~/kubeconfig-github"
echo ""
echo "   # Zmień adres serwera na VPN (10.0.0.4)"
echo "   sed -i 's|server: https://[^:]*:6443|server: https://10.0.0.4:6443|g' ~/kubeconfig-github"
echo ""
echo "   # Sprawdź czy dobrze"
echo "   grep 'server:' ~/kubeconfig-github"
echo ""
echo "   # Zakoduj do base64 (WAŻNE: bez nowych linii)"
echo "   cat ~/kubeconfig-github | base64 -w 0"
echo ""
echo "2. Skopiuj cały output (jedna długa linia) i dodaj jako secret KUBECONFIG_BASE64"
echo ""
echo "3. Alternatywnie, możesz użyć tego polecenia na macOS:"
echo "   cat ~/kubeconfig-github | base64"
echo ""
echo "UWAGA: Upewnij się, że kopiujesz CAŁĄ linię bez dodatkowych spacji czy enterów!"