apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: ${K8S_CA_CERT}
    server: https://10.0.0.4:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    client-certificate-data: ${K8S_CLIENT_CERT}
    client-key-data: ${K8S_CLIENT_KEY}