apiVersion: apps/v1
kind: Deployment
metadata:
  name: edupoint-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: REACT_APP_API_URL
          value: "https://karnetapi-dev.edupoint.pl"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edupoint-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: REACT_APP_API_URL
          value: "https://karnetapi-dev.edupoint.pl"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"