apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucherskit-backend
  labels:
    app: voucherskit-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voucherskit-backend
  template:
    metadata:
      labels:
        app: voucherskit-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: backend
        image: ghcr.io/rafeekpro/edupoint-karnet/backend:main
        ports:
        - containerPort: 8000
        env:
        # Don't use DATABASE_URL to avoid password encoding issues
        # Backend will build it from individual components
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: voucherskit-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: voucherskit-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: voucherskit-config
              key: DB_NAME
        - name: DB_USER
          value: therapy_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voucherskit-prod-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: voucherskit-prod-secrets
              key: JWT_SECRET_KEY
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: voucherskit-config
              key: ENVIRONMENT
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"