apiVersion: v1
kind: Service
metadata:
  name: edupoint-backend
  labels:
    app: edupoint-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: edupoint-backend