apiVersion: v1
kind: Service
metadata:
  name: edupoint-frontend
  labels:
    app: edupoint-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: edupoint-frontend